import { TEMPLATES } from "./const.js";


async function getItemRuneHTML(item) {
    if (item?.system?.runes?.property?.length > 0) {
        const type = item?.type;
        return await getItemRuneHTMLHelper(
            item?.system?.runes?.property.map(rune => ({
                name: getNameLocalization(rune, type),
                uuid: runelist[rune] ?? rune
            }))
        )
    } else {
        return false;
    }
}

async function getItemRuneHTMLHelper(runes) {
    return await TextEditor.enrichHTML(renderTemplate(TEMPLATES.RUNES_ON_ITEM, { runes }))
}

function getNameLocalization(runeDropdownID, type) {
    if (type === 'armor') {
        return game.i18n.localize(`PF2E.ArmorPropertyRune${String(runeDropdownID).charAt(0).toUpperCase() + String(runeDropdownID).slice(1)}`)
    } else if (type === 'weapon') {
        return game.i18n.localize(`PF2E.WeaponPropertyRune${runeDropdownID}.Name`)
    } else {
        return runeDropdownID;
    }
}

const runelist = {
    // Armor Runes
    "acidResistant": "Compendium.pf2e.equipment-srd.Item.Lw3B9DpnyrpXD9Di",
    "advancing": "",
    "aimAiding": "",
    "antimagic": "",
    "assisting": "",
    "bitter": "Compendium.pf2e.equipment-srd.Item.nGZPhGpCxM8U1JXv",
    "coldResistant": "Compendium.pf2e.equipment-srd.Item.Lw3B9DpnyrpXD9Di",
    "deathless": "Compendium.pf2e.equipment-srd.Item.kOEZCUTCPCqCFoJf",
    "electricityResistant": "Compendium.pf2e.equipment-srd.Item.Lw3B9DpnyrpXD9Di",
    "energyAdaptive": "",
    "ethereal": "",
    "fireResistant": "Compendium.pf2e.equipment-srd.Item.Lw3B9DpnyrpXD9Di",
    "fortification": "",
    "glamered": "",
    "gliding": "Compendium.pf2e.equipment-srd.Item.A2Z7Mh8A59wZb5vv",
    "greaterAcidResistant": "Compendium.pf2e.equipment-srd.Item.9CAWAKkZE7dr4FlJ",
    "greaterAdvancing": "",
    "greaterColdResistant": "Compendium.pf2e.equipment-srd.Item.9CAWAKkZE7dr4FlJ",
    "greaterDread": "",
    "greaterElectricityResistant": "Compendium.pf2e.equipment-srd.Item.9CAWAKkZE7dr4FlJ",
    "greaterFireResistant": "Compendium.pf2e.equipment-srd.Item.9CAWAKkZE7dr4FlJ",
    "greaterFortification": "",
    "greaterInvisibility": "Compendium.pf2e.equipment-srd.Item.bxz885LMjLCkpDq3",
    "greaterQuenching": "",
    "greaterReady": "",
    "greaterShadow": "",
    "greaterSlick": "",
    "greaterStanching": "",
    "greaterSwallowSpike": "Compendium.pf2e.equipment-srd.Item.ciykvIC4SFFxIfUw",
    "greaterWinged": "",
    "immovable": "",
    "implacable": "",
    "invisibility": "Compendium.pf2e.equipment-srd.Item.VDudQ4x2ozosAbTb",
    "lesserDread": "",
    "magnetizing": "",
    "majorQuenching": "",
    "majorShadow": "",
    "majorSlick": "",
    "majorStanching": "",
    "majorSwallowSpike": "Compendium.pf2e.equipment-srd.Item.RRFyASbHcdclympe",
    "malleable": "",
    "misleading": "",
    "moderateDread": "",
    "portable": "",
    "quenching": "",
    "raiment": "Compendium.pf2e.equipment-srd.Item.iTxqImupNnm8gvoe",
    "ready": "",
    "rockBraced": "",
    "shadow": "",
    "sinisterKnight": "",
    "sizeChanging": "Compendium.pf2e.equipment-srd.Item.Z5FvYWLEpWVo3PUF",
    "slick": "",
    "soaring": "",
    "spellwatch": "",
    "stanching": "",
    "swallowSpike": "Compendium.pf2e.equipment-srd.Item.BKjwg0TEGioiYpz1",
    "trueQuenching": "",
    "trueStanching": "",
    "winged": "",
    //Weapon Runes
    "ancestralEchoing": "",
    "anchoring": "",
    "ashen": "",
    "astral": "",
    "authorized": "",
    "bane": "",
    "bloodbane": "",
    "bloodthirsty": "",
    "bolkasBlessing": "",
    "brilliant": "Compendium.pf2e.equipment-srd.Item.LbdnZFlyLFdAE617",
    "called": "Compendium.pf2e.equipment-srd.Item.QHc7AnKoMpcqsI2d",
    "coating": "",
    "conducting": "Compendium.pf2e.actionspf2e.Item.BKnN9la3WNrRgZ6n",
    "corrosive": "",
    "crushing": "",
    "cunning": "Compendium.pf2e.equipment-srd.Item.T4gTHDKJ0HI10p3y",
    "dancing": "",
    "decaying": "",
    "deathdrinking": "Compendium.pf2e.equipment-srd.Item.4DXupoMmwenFn4Kc",
    "demolishing": "",
    "disrupting": "",
    "earthbinding": "Compendium.pf2e.equipment-srd.Item.OClYfRHzoynib6wX",
    "energizing": "Compendium.pf2e.equipment-srd.Item.Qqh586pudsEqITUk",
    "extending": "",
    "fanged": "Compendium.pf2e.equipment-srd.Item.pcGdJvwun0tjrUTz",
    "fearsome": "",
    "flaming": "",
    "flickering": "Compendium.pf2e.equipment-srd.Item.p6RmUi2zCSmjd737",
    "flurrying": "Compendium.pf2e.equipment-srd.Item.GNX0BNOoCSOYPedi",
    "frost": "",
    "ghostTouch": "",
    "giantKilling": "",
    "greaterAnchoring": "",
    "greaterAshen": "",
    "greaterAstral": "",
    "greaterBloodbane": "",
    "greaterBolkasBlessing": "",
    "greaterBrilliant": "",
    "greaterCorrosive": "",
    "greaterCrushing": "",
    "greaterDecaying": "",
    "greaterDisrupting": "",
    "greaterExtending": "",
    "greaterFanged": "Compendium.pf2e.equipment-srd.Item.cvb47A6K1w7RfNiv",
    "greaterFearsome": "",
    "greaterFlaming": "",
    "greaterFrost": "",
    "greaterGiantKilling": "",
    "greaterHauling": "Compendium.pf2e.equipment-srd.Item.o0XXVVymB8kluwLK",
    "greaterImpactful": "",
    "greaterKolssOath": "",
    "greaterRooting": "",
    "greaterShock": "",
    "greaterThundering": "",
    "greaterTruddsStrength": "",
    "grievous": "",
    "hauling": "Compendium.pf2e.equipment-srd.Item.2ovu1AioLLff9p8w",
    "holy": "Compendium.pf2e.equipment-srd.Item.DH0kB9Wbr5pDeunX",
    "hopeful": "",
    "hooked": "",
    "impactful": "",
    "impossible": "",
    "keen": "",
    "kinWarding": "",
    "kolssOath": "",
    "majorFanged": "Compendium.pf2e.equipment-srd.Item.qL1S3vGfv8Dh5yAE",
    "majorRooting": "",
    "merciful": "",
    "nightmare": "",
    "pacifying": "Compendium.pf2e.equipment-srd.Item.R8I13CDRzvpVXOVe",
    "returning": "",
    "rooting": "",
    "serrating": "",
    "shifting": "Compendium.pf2e.equipment-srd.Item.roeYtwlIe65BPMJ1",
    "shock": "",
    "shockwave": "",
    "spellStoring": "",
    "speed": "",
    "swarming": "",
    "thundering": "",
    "truddsStrength": "",
    "trueRooting": "",
    "underwater": "",
    "unholy": "",
    "vorpal": "",
    "wounding": ""
}

const RUNE_LIST = {
    ancestralEchoing: "",
    sizeChanging: "Compendium.pf2e.equipment-srd.Item.Z5FvYWLEpWVo3PUF",
    fanged: "Compendium.pf2e.equipment-srd.Item.pcGdJvwun0tjrUTz",
    greaterFanged: "Compendium.pf2e.equipment-srd.Item.cvb47A6K1w7RfNiv",
    majorFanged: "Compendium.pf2e.equipment-srd.Item.qL1S3vGfv8Dh5yAE",
    earthbinding: "Compendium.pf2e.equipment-srd.Item.OClYfRHzoynib6wX",
    cunning: "Compendium.pf2e.equipment-srd.Item.T4gTHDKJ0HI10p3y",
    raiment: "Compendium.pf2e.equipment-srd.Item.iTxqImupNnm8gvoe",
    pacifying: "Compendium.pf2e.equipment-srd.Item.R8I13CDRzvpVXOVe",
    swallowSpike: "Compendium.pf2e.equipment-srd.Item.BKjwg0TEGioiYpz1",
    greaterSwallowSpike: "Compendium.pf2e.equipment-srd.Item.ciykvIC4SFFxIfUw",
    majorSwallowSpike: "Compendium.pf2e.equipment-srd.Item.RRFyASbHcdclympe",
    hauling: "Compendium.pf2e.equipment-srd.Item.2ovu1AioLLff9p8w",
    greaterHauling: "Compendium.pf2e.equipment-srd.Item.o0XXVVymB8kluwLK",
    shifting: "Compendium.pf2e.equipment-srd.Item.roeYtwlIe65BPMJ1",
    energizing: "Compendium.pf2e.equipment-srd.Item.Qqh586pudsEqITUk",
    flickering: "Compendium.pf2e.equipment-srd.Item.p6RmUi2zCSmjd737",
    deathless: "Compendium.pf2e.equipment-srd.Item.kOEZCUTCPCqCFoJf",
    called: "Compendium.pf2e.equipment-srd.Item.QHc7AnKoMpcqsI2d",
    flurrying: "Compendium.pf2e.equipment-srd.Item.GNX0BNOoCSOYPedi",
    gliding: "Compendium.pf2e.equipment-srd.Item.A2Z7Mh8A59wZb5vv",
    invisibility: "Compendium.pf2e.equipment-srd.Item.VDudQ4x2ozosAbTb",
    greaterInvisibility: "Compendium.pf2e.equipment-srd.Item.bxz885LMjLCkpDq3",
    deathdrinking: "Compendium.pf2e.equipment-srd.Item.4DXupoMmwenFn4Kc",
    conducting: "Compendium.pf2e.actionspf2e.Item.BKnN9la3WNrRgZ6n",
    holy: "Compendium.pf2e.equipment-srd.Item.DH0kB9Wbr5pDeunX",
    brilliant: "Compendium.pf2e.equipment-srd.Item.LbdnZFlyLFdAE617",
}